/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlackjackRouteImport } from './routes/blackjack'
import { Route as PokerRouteImport } from './routes/poker'
import { Route as RouletteRouteImport } from './routes/roulette'
import { Route as SlotsRouteImport } from './routes/slots'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackjackRoute = BlackjackRouteImport.update({
  id: '/blackjack',
  path: '/blackjack',
  getParentRoute: () => rootRouteImport,
} as any)
const PokerRoute = PokerRouteImport.update({
  id: '/poker',
  path: '/poker',
  getParentRoute: () => rootRouteImport,
} as any)
const RouletteRoute = RouletteRouteImport.update({
  id: '/roulette',
  path: '/roulette',
  getParentRoute: () => rootRouteImport,
} as any)
const SlotsRoute = SlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/poker': typeof PokerRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/poker': typeof PokerRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blackjack': typeof BlackjackRoute
  '/poker': typeof PokerRoute
  '/roulette': typeof RouletteRoute
  '/slots': typeof SlotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blackjack' | '/poker' | '/roulette' | '/slots'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blackjack' | '/poker' | '/roulette' | '/slots'
  id: '__root__' | '/' | '/blackjack' | '/poker' | '/roulette' | '/slots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlackjackRoute: typeof BlackjackRoute
  PokerRoute: typeof PokerRoute
  RouletteRoute: typeof RouletteRoute
  SlotsRoute: typeof SlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blackjack': {
      id: '/blackjack'
      path: '/blackjack'
      fullPath: '/blackjack'
      preLoaderRoute: typeof BlackjackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poker': {
      id: '/poker'
      path: '/poker'
      fullPath: '/poker'
      preLoaderRoute: typeof PokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roulette': {
      id: '/roulette'
      path: '/roulette'
      fullPath: '/roulette'
      preLoaderRoute: typeof RouletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slots': {
      id: '/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof SlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlackjackRoute: BlackjackRoute,
  PokerRoute: PokerRoute,
  RouletteRoute: RouletteRoute,
  SlotsRoute: SlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
